use_frameworks!

platform :ios, '9.0'

target 'MtsInvestUIService_Example' do
  pod 'MtsInvestUIService', :path => '../'

  target 'MtsInvestUIService_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
