// swiftlint:disable all
// Generated using SwiftGen — https://github.com/SwiftGen/SwiftGen

#if os(macOS)
  import AppKit
#elseif os(iOS)
  import UIKit
#elseif os(tvOS) || os(watchOS)
  import UIKit
#endif

// Deprecated typealiases
@available(*, deprecated, renamed: "ColorAsset.Color", message: "This typealias will be removed in SwiftGen 7.0")
internal typealias AssetColorTypeAlias = ColorAsset.Color
@available(*, deprecated, renamed: "ImageAsset.Image", message: "This typealias will be removed in SwiftGen 7.0")
internal typealias AssetImageTypeAlias = ImageAsset.Image

// swiftlint:disable superfluous_disable_command file_length implicit_return

// MARK: - Asset Catalogs

// swiftlint:disable identifier_name line_length nesting type_body_length type_name
internal enum Assets {
  internal enum Colors {
    internal static let accentActive = ColorAsset(name: "accent-active")
    internal static let accentNegative = ColorAsset(name: "accent-negative")
    internal static let accentPositive = ColorAsset(name: "accent-positive")
    internal static let accentWarning = ColorAsset(name: "accent-warning")
    internal static let backgroundHover = ColorAsset(name: "background-hover")
    internal static let backgroundInverted = ColorAsset(name: "background-inverted")
    internal static let backgroundModal = ColorAsset(name: "background-modal")
    internal static let backgroundNavbarIos = ColorAsset(name: "background-navbar-ios")
    internal static let backgroundOverlay = ColorAsset(name: "background-overlay")
    internal static let backgroundPrimaryElevated = ColorAsset(name: "background-primary-elevated")
    internal static let backgroundPrimary = ColorAsset(name: "background-primary")
    internal static let backgroundSecondaryElevated = ColorAsset(name: "background-secondary-elevated")
    internal static let backgroundSecondary = ColorAsset(name: "background-secondary")
    internal static let backgroundStroke = ColorAsset(name: "background-stroke")
    internal static let mtsRed = ColorAsset(name: "mts-red")
    internal static let constantDarkApple = ColorAsset(name: "constant-dark-apple")
    internal static let constantDarkBanana = ColorAsset(name: "constant-dark-banana")
    internal static let constantDarkBlackberry = ColorAsset(name: "constant-dark-blackberry")
    internal static let constantDarkBlueberry = ColorAsset(name: "constant-dark-blueberry")
    internal static let constantDarkCranberry = ColorAsset(name: "constant-dark-cranberry")
    internal static let constantDarkLime = ColorAsset(name: "constant-dark-lime")
    internal static let constantDarkMint = ColorAsset(name: "constant-dark-mint")
    internal static let constantDarkOrange = ColorAsset(name: "constant-dark-orange")
    internal static let constantDarkPlum = ColorAsset(name: "constant-dark-plum")
    internal static let constantDarkRaspberry = ColorAsset(name: "constant-dark-raspberry")
    internal static let constantDarkestApple = ColorAsset(name: "constant-darkest-apple")
    internal static let constantDarkestBanana = ColorAsset(name: "constant-darkest-banana")
    internal static let constantDarkestBlackberry = ColorAsset(name: "constant-darkest-blackberry")
    internal static let constantDarkestBlueberry = ColorAsset(name: "constant-darkest-blueberry")
    internal static let constantDarkestCranberry = ColorAsset(name: "constant-darkest-cranberry")
    internal static let constantDarkestLime = ColorAsset(name: "constant-darkest-lime")
    internal static let constantDarkestMint = ColorAsset(name: "constant-darkest-mint")
    internal static let constantDarkestOrange = ColorAsset(name: "constant-darkest-orange")
    internal static let constantDarkestPlum = ColorAsset(name: "constant-darkest-plum")
    internal static let constantDarkestRaspberry = ColorAsset(name: "constant-darkest-raspberry")
    internal static let constantGreyscale0 = ColorAsset(name: "constant-greyscale0")
    internal static let constantGreyscale100 = ColorAsset(name: "constant-greyscale100")
    internal static let constantGreyscale200 = ColorAsset(name: "constant-greyscale200")
    internal static let constantGreyscale300 = ColorAsset(name: "constant-greyscale300")
    internal static let constantGreyscale400 = ColorAsset(name: "constant-greyscale400")
    internal static let constantGreyscale500 = ColorAsset(name: "constant-greyscale500")
    internal static let constantGreyscale600 = ColorAsset(name: "constant-greyscale600")
    internal static let constantGreyscale700 = ColorAsset(name: "constant-greyscale700")
    internal static let constantGreyscale800 = ColorAsset(name: "constant-greyscale800")
    internal static let constantGreyscale900 = ColorAsset(name: "constant-greyscale900")
    internal static let constantLightApple = ColorAsset(name: "constant-light-apple")
    internal static let constantLightBanana = ColorAsset(name: "constant-light-banana")
    internal static let constantLightBlackberry = ColorAsset(name: "constant-light-blackberry")
    internal static let constantLightBlueberry = ColorAsset(name: "constant-light-blueberry")
    internal static let constantLightCranberry = ColorAsset(name: "constant-light-cranberry")
    internal static let constantLightLime = ColorAsset(name: "constant-light-lime")
    internal static let constantLightMint = ColorAsset(name: "constant-light-mint")
    internal static let constantLightOrange = ColorAsset(name: "constant-light-orange")
    internal static let constantLightPlum = ColorAsset(name: "constant-light-plum")
    internal static let constantLightRaspberry = ColorAsset(name: "constant-light-raspberry")
    internal static let constantLightestApple = ColorAsset(name: "constant-lightest-apple")
    internal static let constantLightestBanana = ColorAsset(name: "constant-lightest-banana")
    internal static let constantLightestBlackberry = ColorAsset(name: "constant-lightest-blackberry")
    internal static let constantLightestBlueberry = ColorAsset(name: "constant-lightest-blueberry")
    internal static let constantLightestCranberry = ColorAsset(name: "constant-lightest-cranberry")
    internal static let constantLightestLime = ColorAsset(name: "constant-lightest-lime")
    internal static let constantLightestMint = ColorAsset(name: "constant-lightest-mint")
    internal static let constantLightestOrange = ColorAsset(name: "constant-lightest-orange")
    internal static let constantLightestPlum = ColorAsset(name: "constant-lightest-plum")
    internal static let constantLightestRaspberry = ColorAsset(name: "constant-lightest-raspberry")
    internal static let constantNormalApple = ColorAsset(name: "constant-normal-apple")
    internal static let constantNormalBanana = ColorAsset(name: "constant-normal-banana")
    internal static let constantNormalBlackberry = ColorAsset(name: "constant-normal-blackberry")
    internal static let constantNormalBlueberry = ColorAsset(name: "constant-normal-blueberry")
    internal static let constantNormalCranberry = ColorAsset(name: "constant-normal-cranberry")
    internal static let constantNormalLime = ColorAsset(name: "constant-normal-lime")
    internal static let constantNormalMint = ColorAsset(name: "constant-normal-mint")
    internal static let constantNormalOrange = ColorAsset(name: "constant-normal-orange")
    internal static let constantNormalPlum = ColorAsset(name: "constant-normal-plum")
    internal static let constantNormalRaspberry = ColorAsset(name: "constant-normal-raspberry")
    internal static let controlsActiveTabbar = ColorAsset(name: "controls-active-tabbar")
    internal static let controlsAlternative = ColorAsset(name: "controls-alternative")
    internal static let controlsInactiveTabbar = ColorAsset(name: "controls-inactive-tabbar")
    internal static let controlsInactive = ColorAsset(name: "controls-inactive")
    internal static let controlsPrimaryActive = ColorAsset(name: "controls-primary-active")
    internal static let controlsSecondaryActive = ColorAsset(name: "controls-secondary-active")
    internal static let controlsTertiaryActive = ColorAsset(name: "controls-tertiary-active")
    internal static let iconsPrimary = ColorAsset(name: "icons-primary")
    internal static let iconsSecondary = ColorAsset(name: "icons-secondary")
    internal static let iconsTertiary = ColorAsset(name: "icons-tertiary")
    internal static let textHeadline = ColorAsset(name: "text-headline")
    internal static let textInverted = ColorAsset(name: "text-inverted")
    internal static let textNegative = ColorAsset(name: "text-negative")
    internal static let textPositive = ColorAsset(name: "text-positive")
    internal static let textPrimaryLink = ColorAsset(name: "text-primary-link")
    internal static let textPrimary = ColorAsset(name: "text-primary")
    internal static let textSecondaryLink = ColorAsset(name: "text-secondary-link")
    internal static let textSecondary = ColorAsset(name: "text-secondary")
    internal static let textTertiary = ColorAsset(name: "text-tertiary")
  }
  internal enum Images {
    internal static let arrowLeft = ImageAsset(name: "arrow_left")
    internal static let arrowRight = ImageAsset(name: "arrow_right")
    internal static let cross = ImageAsset(name: "cross")
    internal static let addressAccessoryIndicator = ImageAsset(name: "AddressAccessoryIndicator")
    internal static let applicationIcon = ImageAsset(name: "ApplicationIcon")
    internal static let eyeClosed = ImageAsset(name: "eye_closed")
    internal static let eyeOpened = ImageAsset(name: "eye_opened")
    internal static let backgroundBrokerageAccountNotOpened = ImageAsset(name: "background_brokerage_account_not_opened")
    internal static let backgroundBrokerageAccountOpened = ImageAsset(name: "background_brokerage_account_opened")
    internal static let brokerageCurrencyEur = ImageAsset(name: "brokerage_currency_eur")
    internal static let brokerageCurrencyRub = ImageAsset(name: "brokerage_currency_rub")
    internal static let brokerageCurrencyUsd = ImageAsset(name: "brokerage_currency_usd")
    internal static let attentionCircleGrayIcon = ImageAsset(name: "attention-circle-gray-icon")
    internal static let attentionCircleOrangeIcon = ImageAsset(name: "attention-circle-orange-icon")
    internal static let attentionCircleRedIcon = ImageAsset(name: "attention-circle-red-icon")
    internal static let attentionRedIcon = ImageAsset(name: "attention-red-icon")
    internal static let attentionYellowIcon = ImageAsset(name: "attention-yellow-icon")
    internal static let binGrayIcon = ImageAsset(name: "bin-gray-icon")
    internal static let checkboxSquareEmpty = ImageAsset(name: "checkbox-square-empty")
    internal static let checkboxSquareRed = ImageAsset(name: "checkbox-square-red")
    internal static let clockGrayIcon = ImageAsset(name: "clock-gray-icon")
    internal static let closeCrossCircleRedIcon = ImageAsset(name: "close-cross-circle-red-icon")
    internal static let closeGrayIcon = ImageAsset(name: "close-gray-icon")
    internal static let closeIconBlack = ImageAsset(name: "close_icon_black")
    internal static let doneSuccessIcon = ImageAsset(name: "done-success-icon")
    internal static let inProgressIcon = ImageAsset(name: "in-progress-icon")
    internal static let infoCircleBlueIcon = ImageAsset(name: "info-circle-blue-icon")
    internal static let mtsbankLogo = ImageAsset(name: "mtsbank-logo")
    internal static let stopIcon = ImageAsset(name: "stop-icon")
    internal static let bondInfo = ImageAsset(name: "bondInfo")
    internal static let brokerageOperationOther = ImageAsset(name: "brokerage-operation-other")
    internal static let brokerageOperationRefill = ImageAsset(name: "brokerage-operation-refill")
    internal static let brokerageOperationWithdrawal = ImageAsset(name: "brokerage-operation-withdrawal")
    internal static let infoSolidBlackIcon = ImageAsset(name: "info-solid-black-icon")
    internal static let grayInfo = ImageAsset(name: "gray_info")
    internal static let iconAlertRed = ImageAsset(name: "icon_alert_red")
    internal static let icEuFlag = ImageAsset(name: "icEuFlag")
    internal static let icRfFlag = ImageAsset(name: "icRfFlag")
    internal static let icUsFlag = ImageAsset(name: "icUsFlag")
    internal static let backgroundDuNotOpened = ImageAsset(name: "background_du_not_opened")
    internal static let backgroundDuOpened = ImageAsset(name: "background_du_opened")
    internal static let allStrategies = ImageAsset(name: "all_strategies")
    internal static let boldAttention = ImageAsset(name: "bold_attention")
    internal static let checkmarkDisabled = ImageAsset(name: "checkmark_disabled")
    internal static let checkmarkOff = ImageAsset(name: "checkmark_off")
    internal static let checkmarkOn = ImageAsset(name: "checkmark_on")
    internal static let duEmptyChart = ImageAsset(name: "duEmptyChart")
    internal static let duCheckmarkChecked = ImageAsset(name: "du_checkmark_checked")
    internal static let duCheckmarkUnchecked = ImageAsset(name: "du_checkmark_unchecked")
    internal static let duItem = ImageAsset(name: "du_item")
    internal static let duItemGrey = ImageAsset(name: "du_item_grey")
    internal static let icDuMoneyRefund = ImageAsset(name: "ic_du_money_refund")
    internal static let icGrayClear = ImageAsset(name: "ic_gray_clear")
    internal static let icListOfStrategies = ImageAsset(name: "ic_list_of_strategies")
    internal static let icRoundedCheckmarkOff = ImageAsset(name: "ic_rounded_checkmark_off")
    internal static let icRoundedCheckmarkOn = ImageAsset(name: "ic_rounded_checkmark_on")
    internal static let icStrategyCurrencyRUB = ImageAsset(name: "ic_strategy_currency_RUB")
    internal static let icStrategyCurrencyUSD = ImageAsset(name: "ic_strategy_currency_USD")
    internal static let icStrategyPlaceholder = ImageAsset(name: "ic_strategy_placeholder")
    internal static let infoGray = ImageAsset(name: "info_gray")
    internal static let questionIcon = ImageAsset(name: "question_icon")
    internal static let questionIconGrey = ImageAsset(name: "question_icon_grey")
    internal static let questionIconWhite = ImageAsset(name: "question_icon_white")
    internal static let icEurGrey = ImageAsset(name: "icEur_grey")
    internal static let icRubGrey = ImageAsset(name: "icRub_grey")
    internal static let icUsdGrey = ImageAsset(name: "icUsd_grey")
    internal static let icArrowDown = ImageAsset(name: "icArrowDown")
    internal static let icArrowNeutralDown = ImageAsset(name: "icArrowNeutralDown")
    internal static let icArrowNeutralUp = ImageAsset(name: "icArrowNeutralUp")
    internal static let icArrowUp = ImageAsset(name: "icArrowUp")
    internal static let icOpenModal = ImageAsset(name: "icOpenModal")
    internal static let listClick = ImageAsset(name: "list_click")
    internal static let mtsInvestLogo = ImageAsset(name: "mts_invest_logo")
    internal static let quoteLeft = ImageAsset(name: "quote_left")
    internal static let quoteRight = ImageAsset(name: "quote_right")
    internal static let testArticleImage = ImageAsset(name: "testArticleImage")
    internal static let testFBicon = ImageAsset(name: "testFBicon")
    internal static let currencyRubOff = ImageAsset(name: "currency_rubOff")
    internal static let currencyRubOn = ImageAsset(name: "currency_rubOn")
    internal static let currencyUsdOff = ImageAsset(name: "currency_usdOff")
    internal static let currencyUsdOn = ImageAsset(name: "currency_usdOn")
    internal static let iconDollarBio = ImageAsset(name: "icon_dollar_bio")
    internal static let iconDollarBonds = ImageAsset(name: "icon_dollar_bonds")
    internal static let iconDollarReserve = ImageAsset(name: "icon_dollar_reserve")
    internal static let iconDollarStocks = ImageAsset(name: "icon_dollar_stocks")
    internal static let iconRubleBonds = ImageAsset(name: "icon_ruble_bonds")
    internal static let iconRubleReserve = ImageAsset(name: "icon_ruble_reserve")
    internal static let iconRubleStocks = ImageAsset(name: "icon_ruble_stocks")
    internal static let iconTrustManagement = ImageAsset(name: "icon_trustManagement")
    internal static let backgroundMtsBrokerNotOpened = ImageAsset(name: "background_mts_broker_not_opened")
    internal static let backgroundMtsBrokerOpened = ImageAsset(name: "background_mts_broker_opened")
    internal static let grayWatchBig = ImageAsset(name: "gray_watch_big")
    internal static let icWhiteArrowUp = ImageAsset(name: "ic_white_arrow_up")
    internal static let moreMenuAbout = ImageAsset(name: "more_menu_about")
    internal static let moreMenuAboutApp = ImageAsset(name: "more_menu_aboutApp")
    internal static let moreMenuContacts = ImageAsset(name: "more_menu_contacts")
    internal static let moreMenuFeedback = ImageAsset(name: "more_menu_feedback")
    internal static let moreMenuHelp = ImageAsset(name: "more_menu_help")
    internal static let moreMenuProfile = ImageAsset(name: "more_menu_profile")
    internal static let backgroundPifNotOpened = ImageAsset(name: "background_pif_not_opened")
    internal static let backgroundPifOpened = ImageAsset(name: "background_pif_opened")
    internal static let iconAllFilter = ImageAsset(name: "icon_all_filter")
    internal static let iconRubFilter = ImageAsset(name: "icon_rub_filter")
    internal static let iconUsdFilter = ImageAsset(name: "icon_usd_filter")
    internal static let iconDown = ImageAsset(name: "icon_down")
    internal static let iconPlus = ImageAsset(name: "icon_plus")
    internal static let iconProfit = ImageAsset(name: "icon_profit")
    internal static let iconRoboAdvisor = ImageAsset(name: "icon_roboAdvisor")
    internal static let iconRoundPlus = ImageAsset(name: "icon_round_plus")
    internal static let iconSort = ImageAsset(name: "icon_sort")
    internal static let warningmarkGray = ImageAsset(name: "warningmark_gray")
    internal static let warningmarkRed = ImageAsset(name: "warningmark_red")
    internal static let icAboutApp = ImageAsset(name: "ic_about_app")
    internal static let icAboutCompany = ImageAsset(name: "ic_about_company")
    internal static let icAllApps = ImageAsset(name: "ic_all_apps")
    internal static let icArrowNext = ImageAsset(name: "ic_arrow_next")
    internal static let icContacts = ImageAsset(name: "ic_contacts")
    internal static let icSupport = ImageAsset(name: "ic_support")
    internal static let icWriteToDev = ImageAsset(name: "ic_write_to_dev")
    internal static let noProfileImage = ImageAsset(name: "no_profile_image")
    internal static let docUnavailable = ImageAsset(name: "docUnavailable")
    internal static let iconApplicationFormBuy = ImageAsset(name: "icon_application_form_buy")
    internal static let iconApplicationFormChange = ImageAsset(name: "icon_application_form_change")
    internal static let iconApplicationFormSell = ImageAsset(name: "icon_application_form_sell")
    internal static let iconCard = ImageAsset(name: "icon_card")
    internal static let iconDollarBuy = ImageAsset(name: "icon_dollar_buy")
    internal static let iconDollarChange = ImageAsset(name: "icon_dollar_change")
    internal static let iconDollarSell = ImageAsset(name: "icon_dollar_sell")
    internal static let iconRedCase = ImageAsset(name: "icon_red_case")
    internal static let iconRedExclamationMark = ImageAsset(name: "icon_red_exclamation_mark")
    internal static let iconRubleBuy = ImageAsset(name: "icon_ruble_buy")
    internal static let iconRubleChange = ImageAsset(name: "icon_ruble_change")
    internal static let iconRubleSell = ImageAsset(name: "icon_ruble_sell")
    internal static let iconWatch = ImageAsset(name: "icon_watch")
    internal static let iconIntro = ImageAsset(name: "icon_intro")
    internal static let riskImage = ImageAsset(name: "risk_image")
    internal static let emptyCheckmark = ImageAsset(name: "empty_checkmark")
    internal static let filledCheckmark = ImageAsset(name: "filled_checkmark")
    internal static let icDarkPen = ImageAsset(name: "ic_dark_pen")
    internal static let backgroundSavingsAccountNotOpened = ImageAsset(name: "background_savings_account_not_opened")
    internal static let backgroundSavingsAccountOpened = ImageAsset(name: "background_savings_account_opened")
    internal static let doc = ImageAsset(name: "doc")
    internal static let iconAlert = ImageAsset(name: "icon_alert")
    internal static let iconDocuments = ImageAsset(name: "icon_documents")
    internal static let iconRequisites = ImageAsset(name: "icon_requisites")
    internal static let image = ImageAsset(name: "Image")
    internal static let moreActive = ImageAsset(name: "more_active")
    internal static let moreInactive = ImageAsset(name: "more_inactive")
    internal static let operationsActive = ImageAsset(name: "operations_active")
    internal static let operationsInactive = ImageAsset(name: "operations_inactive")
    internal static let portfolioActive = ImageAsset(name: "portfolio_active")
    internal static let portfolioInactive = ImageAsset(name: "portfolio_inactive")
    internal static let showcaseActive = ImageAsset(name: "showcase_active")
    internal static let showcaseInactive = ImageAsset(name: "showcase_inactive")
    internal static let actionClose = ImageAsset(name: "action_close")
    internal static let addCardPlus = ImageAsset(name: "add_card_plus")
    internal static let approveImage = ImageAsset(name: "approve_image")
    internal static let arrowDown = ImageAsset(name: "arrow_down")
    internal static let arrowDownDark = ImageAsset(name: "arrow_down_dark")
    internal static let arrowIcon = ImageAsset(name: "arrow_icon")
    internal static let arrowUp = ImageAsset(name: "arrow_up")
    internal static let attenionOrange = ImageAsset(name: "attenion_orange")
    internal static let bookmarkChecked = ImageAsset(name: "bookmark_checked")
    internal static let bookmarkUnchecked = ImageAsset(name: "bookmark_unchecked")
    internal static let checkboxInactive = ImageAsset(name: "checkbox_inactive")
    internal static let checked = ImageAsset(name: "checked")
    internal static let checkmarkCheked = ImageAsset(name: "checkmark_cheked")
    internal static let checkmarkGray = ImageAsset(name: "checkmark_gray")
    internal static let checkmarkInactive = ImageAsset(name: "checkmark_inactive")
    internal static let checkmarkRed = ImageAsset(name: "checkmark_red")
    internal static let checkmarkUncheked = ImageAsset(name: "checkmark_uncheked")
    internal static let closeButtonDrawer = ImageAsset(name: "closeButtonDrawer")
    internal static let dcl = ImageAsset(name: "dcl")
    internal static let docIcon = ImageAsset(name: "doc_icon")
    internal static let documentIcon = ImageAsset(name: "document_icon")
    internal static let duChartUp = ImageAsset(name: "du_chart_up")
    internal static let errorMan = ImageAsset(name: "error_man")
    internal static let failDocImage = ImageAsset(name: "fail_doc_image")
    internal static let failImage = ImageAsset(name: "fail_image")
    internal static let feedbackIcon = ImageAsset(name: "feedback_icon")
    internal static let graphSkeleton = ImageAsset(name: "graph_skeleton")
    internal static let icAdd = ImageAsset(name: "icAdd")
    internal static let icArrowRight = ImageAsset(name: "icArrowRight")
    internal static let icAttention = ImageAsset(name: "icAttention")
    internal static let icAttentionSmall = ImageAsset(name: "icAttentionSmall")
    internal static let icAttentionSmallCopy2 = ImageAsset(name: "icAttentionSmallCopy2")
    internal static let icAttentionYellow = ImageAsset(name: "icAttentionYellow")
    internal static let icBigTrash = ImageAsset(name: "icBigTrash")
    internal static let icCheckmarkOn = ImageAsset(name: "icCheckmarkOn")
    internal static let icCoinsCopy3 = ImageAsset(name: "icCoinsCopy3")
    internal static let icContactsCall = ImageAsset(name: "icContactsCall")
    internal static let icDeleteCard = ImageAsset(name: "icDeleteCard")
    internal static let icErrorUpdate = ImageAsset(name: "icErrorUpdate")
    internal static let icFavoriteWhite = ImageAsset(name: "icFavorite_white")
    internal static let icFavoriteWhiteChecked = ImageAsset(name: "icFavorite_white_checked")
    internal static let icMail = ImageAsset(name: "icMail")
    internal static let icNoData = ImageAsset(name: "icNoData")
    internal static let icOperations = ImageAsset(name: "icOperations")
    internal static let icPencilRedact = ImageAsset(name: "icPencilRedact")
    internal static let icRadiobutActive = ImageAsset(name: "icRadiobut_active")
    internal static let icRadiobutInactive = ImageAsset(name: "icRadiobut_inactive")
    internal static let icSearch = ImageAsset(name: "icSearch")
    internal static let icTrash = ImageAsset(name: "icTrash")
    internal static let icDUStrategyShevron = ImageAsset(name: "ic_DUStrategyShevron")
    internal static let icBarFavourite = ImageAsset(name: "ic_bar_favourite")
    internal static let icBarShare = ImageAsset(name: "ic_bar_share")
    internal static let icBuyingStatus = ImageAsset(name: "ic_buyingStatus")
    internal static let icDislike = ImageAsset(name: "ic_dislike")
    internal static let icDropdownArrow = ImageAsset(name: "ic_dropdown_arrow")
    internal static let icFacebook = ImageAsset(name: "ic_facebook")
    internal static let icFeedCloseCard = ImageAsset(name: "ic_feed_close_card")
    internal static let icInfo = ImageAsset(name: "ic_info")
    internal static let icLike = ImageAsset(name: "ic_like")
    internal static let icMycountArrow = ImageAsset(name: "ic_mycount_arrow")
    internal static let icOpenBrokerage = ImageAsset(name: "ic_openBrokerage")
    internal static let icPurchaseCanceled = ImageAsset(name: "ic_purchaseCanceled")
    internal static let icPurchaseInProgress = ImageAsset(name: "ic_purchaseInProgress")
    internal static let icRadioGrayInactive = ImageAsset(name: "ic_radio_gray_inactive")
    internal static let icRedRadioEnabled = ImageAsset(name: "ic_red_radio_enabled")
    internal static let icSortDescriptorDeselected = ImageAsset(name: "ic_sort_descriptor_deselected")
    internal static let icSortDescriptorSelected = ImageAsset(name: "ic_sort_descriptor_selected")
    internal static let icSuccess = ImageAsset(name: "ic_success")
    internal static let icSuccessGreen = ImageAsset(name: "ic_success_green")
    internal static let icon24IcCheckMark = ImageAsset(name: "icon24IcCheckMark")
    internal static let iconBack = ImageAsset(name: "icon_back")
    internal static let iconClose = ImageAsset(name: "icon_close")
    internal static let iconCloseGray = ImageAsset(name: "icon_close_gray")
    internal static let iconDelete = ImageAsset(name: "icon_delete")
    internal static let iconFaceId = ImageAsset(name: "icon_faceId")
    internal static let iconGosuslugi = ImageAsset(name: "icon_gosuslugi")
    internal static let iconInfo = ImageAsset(name: "icon_info")
    internal static let iconInfoBlack = ImageAsset(name: "icon_info_black")
    internal static let iconInfoGrey = ImageAsset(name: "icon_info_grey")
    internal static let iconRoundPlusBlue = ImageAsset(name: "icon_round_plus_blue")
    internal static let iconThumb = ImageAsset(name: "icon_thumb")
    internal static let iconThumb2 = ImageAsset(name: "icon_thumb2")
    internal static let iconTouchId = ImageAsset(name: "icon_touchId")
    internal static let iconWhitePlus = ImageAsset(name: "icon_white_plus")
    internal static let jcb = ImageAsset(name: "jcb")
    internal static let launchImage = ImageAsset(name: "launch_image")
    internal static let launchLogo = ImageAsset(name: "launch_logo")
    internal static let listIcon = ImageAsset(name: "list_icon")
    internal static let logoVector = ImageAsset(name: "logo_vector")
    internal static let maestro = ImageAsset(name: "maestro")
    internal static let mastercard = ImageAsset(name: "mastercard")
    internal static let mir = ImageAsset(name: "mir")
    internal static let mtsLogoOld = ImageAsset(name: "mts-logo-old")
    internal static let operationRefill = ImageAsset(name: "operation_refill")
    internal static let operationWithdrawal = ImageAsset(name: "operation_withdrawal")
    internal static let pinActive = ImageAsset(name: "pin_active")
    internal static let pinInactive = ImageAsset(name: "pin_inactive")
    internal static let pinIncorrect = ImageAsset(name: "pin_incorrect")
    internal static let quotaDown = ImageAsset(name: "quota_down")
    internal static let quotaUp = ImageAsset(name: "quota_up")
    internal static let rectangleRounded10p = ImageAsset(name: "rectangle-rounded-10p")
    internal static let removeCardButton = ImageAsset(name: "remove_card_button")
    internal static let shareGrey = ImageAsset(name: "share_grey")
    internal static let spbForeignShares = ImageAsset(name: "spb_foreign_shares")
    internal static let ssl = ImageAsset(name: "ssl")
    internal static let support = ImageAsset(name: "support")
    internal static let supportGray = ImageAsset(name: "support_gray")
    internal static let unchecked = ImageAsset(name: "unchecked")
    internal static let unknownCard = ImageAsset(name: "unknown_card")
    internal static let update = ImageAsset(name: "update")
    internal static let visa = ImageAsset(name: "visa")
  }
}
// swiftlint:enable identifier_name line_length nesting type_body_length type_name

// MARK: - Implementation Details

internal final class ColorAsset {
  internal fileprivate(set) var name: String

  #if os(macOS)
  internal typealias Color = NSColor
  #elseif os(iOS) || os(tvOS) || os(watchOS)
  internal typealias Color = UIColor
  #endif

  @available(iOS 11.0, tvOS 11.0, watchOS 4.0, macOS 10.13, *)
  internal private(set) lazy var color: Color = {
    guard let color = Color(asset: self) else {
      fatalError("Unable to load color asset named \(name).")
    }
    return color
  }()

  fileprivate init(name: String) {
    self.name = name
  }
}

internal extension ColorAsset.Color {
  @available(iOS 11.0, tvOS 11.0, watchOS 4.0, macOS 10.13, *)
  convenience init?(asset: ColorAsset) {
    let bundle = BundleToken.bundle
    #if os(iOS) || os(tvOS)
    self.init(named: asset.name, in: bundle, compatibleWith: nil)
    #elseif os(macOS)
    self.init(named: NSColor.Name(asset.name), bundle: bundle)
    #elseif os(watchOS)
    self.init(named: asset.name)
    #endif
  }
}

internal struct ImageAsset {
  internal fileprivate(set) var name: String

  #if os(macOS)
  internal typealias Image = NSImage
  #elseif os(iOS) || os(tvOS) || os(watchOS)
  internal typealias Image = UIImage
  #endif

  internal var image: Image {
    let bundle = BundleToken.bundle
    #if os(iOS) || os(tvOS)
    let image = Image(named: name, in: bundle, compatibleWith: nil)
    #elseif os(macOS)
    let name = NSImage.Name(self.name)
    let image = (bundle == .main) ? NSImage(named: name) : bundle.image(forResource: name)
    #elseif os(watchOS)
    let image = Image(named: name)
    #endif
    guard let result = image else {
      fatalError("Unable to load image asset named \(name).")
    }
    return result
  }
}

internal extension ImageAsset.Image {
  @available(macOS, deprecated,
    message: "This initializer is unsafe on macOS, please use the ImageAsset.image property")
  convenience init?(asset: ImageAsset) {
    #if os(iOS) || os(tvOS)
    let bundle = BundleToken.bundle
    self.init(named: asset.name, in: bundle, compatibleWith: nil)
    #elseif os(macOS)
    self.init(named: NSImage.Name(asset.name))
    #elseif os(watchOS)
    self.init(named: asset.name)
    #endif
  }
}

// swiftlint:disable convenience_type
private final class BundleToken {
  static let bundle: Bundle = {
    #if SWIFT_PACKAGE
    return Bundle.module
    #else
    return Bundle(for: BundleToken.self)
    #endif
  }()
}
// swiftlint:enable convenience_type
